<?php

class CargoTableSeeder extends Seeder {

    public function run()
    {
        DB::table('cargos')->delete();

        Cargo::create(array('id'=>1,'nombre'=>'AUXILIAR DE COORDINACION'));
		Cargo::create(array('id'=>2,'nombre'=>'AUXILIAR DE COORDINACION INTERNA'));
		Cargo::create(array('id'=>3,'nombre'=>'AUXILIAR DE DIRECCION GENERAL'));
		Cargo::create(array('id'=>4,'nombre'=>'AUXILIAR DE DIRECCION GENERAL A'));
		Cargo::create(array('id'=>5,'nombre'=>'CHOFER'));
		Cargo::create(array('id'=>6,'nombre'=>'CHOFER IFAI'));
		Cargo::create(array('id'=>7,'nombre'=>'COMISIONADO'));
		Cargo::create(array('id'=>8,'nombre'=>'CONTRALORIA'));
		Cargo::create(array('id'=>9,'nombre'=>'DEPARTAMENTO A'));
		Cargo::create(array('id'=>10,'nombre'=>'DEPARTAMENTO DE ANALISIS'));
		Cargo::create(array('id'=>11,'nombre'=>'DEPARTAMENTO DE ANALISIS DE ACCESO A LA INFORMACION A'));
		Cargo::create(array('id'=>12,'nombre'=>'DEPARTAMENTO DE ANALISIS DE ACCESO A LA INFORMACION B'));
		Cargo::create(array('id'=>13,'nombre'=>'DEPARTAMENTO DE ANALISIS DE PROTECCION DE DATOS A'));
		Cargo::create(array('id'=>14,'nombre'=>'DEPARTAMENTO DE ANALISIS DE PROTECCION DE DATOS B'));
		Cargo::create(array('id'=>15,'nombre'=>'DEPARTAMENTO DE ANALISIS NORMATIVOS'));
		Cargo::create(array('id'=>16,'nombre'=>'DEPARTAMENTO DE ANALISIS Y ESTUDIOS DE PONENCIA A'));
		Cargo::create(array('id'=>17,'nombre'=>'DEPARTAMENTO DE ANALISIS Y ESTUDIOS DE PONENCIA B'));
		Cargo::create(array('id'=>18,'nombre'=>'DEPARTAMENTO DE APLICACIONES WEB A'));
		Cargo::create(array('id'=>19,'nombre'=>'DEPARTAMENTO DE APLICACIONES WEB B'));
		Cargo::create(array('id'=>20,'nombre'=>'DEPARTAMENTO DE APOYO A ESTADOS Y MUNICIPIOS'));
		Cargo::create(array('id'=>21,'nombre'=>'DEPARTAMENTO DE APOYO LOGISTICO'));
		Cargo::create(array('id'=>22,'nombre'=>'DEPARTAMENTO DE APOYO TECNICO'));
		Cargo::create(array('id'=>23,'nombre'=>'DEPARTAMENTO DE ASESORIA PERSONALIZADA'));
		Cargo::create(array('id'=>24,'nombre'=>'DEPARTAMENTO DE ASESORIA Y COORDINACION A'));
		Cargo::create(array('id'=>25,'nombre'=>'DEPARTAMENTO DE ASESORIA Y COORDINACION B'));
		Cargo::create(array('id'=>26,'nombre'=>'DEPARTAMENTO DE ASUNTOS INTERNACIONALES DE ACCESO A'));
		Cargo::create(array('id'=>27,'nombre'=>'DEPARTAMENTO DE ASUNTOS INTERNACIONALES DE ACCESO B'));
		Cargo::create(array('id'=>28,'nombre'=>'DEPARTAMENTO DE ASUNTOS INTERNACIONALES DE DATOS A'));
		Cargo::create(array('id'=>29,'nombre'=>'DEPARTAMENTO DE ASUNTOS INTERNACIONALES DE DATOS B'));
		Cargo::create(array('id'=>30,'nombre'=>'DEPARTAMENTO DE ATENCION PROCESAL A'));
		Cargo::create(array('id'=>31,'nombre'=>'DEPARTAMENTO DE ATENCION PROCESAL B'));
		Cargo::create(array('id'=>32,'nombre'=>'DEPARTAMENTO DE ATENCION REGIONAL CENTRO A'));
		Cargo::create(array('id'=>33,'nombre'=>'DEPARTAMENTO DE ATENCION REGIONAL CENTRO B'));
		Cargo::create(array('id'=>34,'nombre'=>'DEPARTAMENTO DE ATENCION REGIONAL NORTE A'));
		Cargo::create(array('id'=>35,'nombre'=>'DEPARTAMENTO DE ATENCION REGIONAL NORTE B'));
		Cargo::create(array('id'=>36,'nombre'=>'DEPARTAMENTO DE ATENCION REGIONAL SUR A'));
		Cargo::create(array('id'=>37,'nombre'=>'DEPARTAMENTO DE ATENCION REGIONAL SUR B'));
		Cargo::create(array('id'=>38,'nombre'=>'DEPARTAMENTO DE AUDIENCIAS A'));
		Cargo::create(array('id'=>39,'nombre'=>'DEPARTAMENTO DE AUDIENCIAS B'));
		Cargo::create(array('id'=>40,'nombre'=>'DEPARTAMENTO DE CALIDAD DE SOLUCIONES TECNOLOGICAS'));
		Cargo::create(array('id'=>41,'nombre'=>'DEPARTAMENTO DE CERTIFICACION'));
		Cargo::create(array('id'=>42,'nombre'=>'DEPARTAMENTO DE CLASIFICACION'));
		Cargo::create(array('id'=>43,'nombre'=>'DEPARTAMENTO DE CONSULTAS NORMATIVAS'));
		Cargo::create(array('id'=>44,'nombre'=>'DEPARTAMENTO DE CONTABILIDAD'));
		Cargo::create(array('id'=>45,'nombre'=>'DEPARTAMENTO DE CONTRATACIONES'));
		Cargo::create(array('id'=>46,'nombre'=>'DEPARTAMENTO DE CONTROL DE ARCHIVOS'));
		Cargo::create(array('id'=>47,'nombre'=>'DEPARTAMENTO DE CONTROL DE GESTION'));
		Cargo::create(array('id'=>48,'nombre'=>'DEPARTAMENTO DE CONTROL DE INGRESOS Y NOMINA'));
		Cargo::create(array('id'=>49,'nombre'=>'DEPARTAMENTO DE CONTROL ESTADISTICO'));
		Cargo::create(array('id'=>50,'nombre'=>'DEPARTAMENTO DE CONTROL PATRIMONIAL'));
		Cargo::create(array('id'=>51,'nombre'=>'DEPARTAMENTO DE CONTROL PRESUPUESTAL'));
		Cargo::create(array('id'=>52,'nombre'=>'DEPARTAMENTO DE CONVENIOS Y RECOMENDACIONES'));
		Cargo::create(array('id'=>53,'nombre'=>'DEPARTAMENTO DE COORDINACION Y SEGUIMIENTO'));
		Cargo::create(array('id'=>54,'nombre'=>'DEPARTAMENTO DE DESARROLLO DE CAPACITACION DE ACCESO'));
		Cargo::create(array('id'=>55,'nombre'=>'DEPARTAMENTO DE DESARROLLO DE CAPACITACION DE DATOS A'));
		Cargo::create(array('id'=>56,'nombre'=>'DEPARTAMENTO DE DESARROLLO DE CAPACITACION DE DATOS B'));
		Cargo::create(array('id'=>57,'nombre'=>'DEPARTAMENTO DE DESARROLLO DE SERVICIOS A LOS PARTICULARES'));
		Cargo::create(array('id'=>58,'nombre'=>'DEPARTAMENTO DE DESARROLLO DE SISTEMAS'));
		Cargo::create(array('id'=>59,'nombre'=>'DEPARTAMENTO DE DESARROLLO DE SISTEMAS DE PROTECCION DE DATOS PERSONALES'));
		Cargo::create(array('id'=>60,'nombre'=>'DEPARTAMENTO DE DISEÑO GRAFICO'));
		Cargo::create(array('id'=>61,'nombre'=>'DEPARTAMENTO DE ENLACE'));
		Cargo::create(array('id'=>62,'nombre'=>'DEPARTAMENTO DE ESTUDIOS'));
		Cargo::create(array('id'=>63,'nombre'=>'DEPARTAMENTO DE ESTUDIOS NORMATIVOS'));
		Cargo::create(array('id'=>64,'nombre'=>'DEPARTAMENTO DE EVALUACION Y MEJORAS DE LA GESTION'));
		Cargo::create(array('id'=>65,'nombre'=>'DEPARTAMENTO DE GESTION'));
		Cargo::create(array('id'=>66,'nombre'=>'DEPARTAMENTO DE INFORMACION'));
		Cargo::create(array('id'=>67,'nombre'=>'DEPARTAMENTO DE INVESTIGACION A'));
		Cargo::create(array('id'=>68,'nombre'=>'DEPARTAMENTO DE INVESTIGACION B'));
		Cargo::create(array('id'=>69,'nombre'=>'DEPARTAMENTO DE LO CONSULTIVO A'));
		Cargo::create(array('id'=>70,'nombre'=>'DEPARTAMENTO DE LO CONSULTIVO B'));
		Cargo::create(array('id'=>71,'nombre'=>'DEPARTAMENTO DE LO CONTENCIOSO DE ACCESO'));
		Cargo::create(array('id'=>72,'nombre'=>'DEPARTAMENTO DE LO CONTENCIOSO DE DATOS A'));
		Cargo::create(array('id'=>73,'nombre'=>'DEPARTAMENTO DE LO CONTENCIOSO DE DATOS B'));
		Cargo::create(array('id'=>74,'nombre'=>'DEPARTAMENTO DE MANTENIMIENTO'));
		Cargo::create(array('id'=>75,'nombre'=>'DEPARTAMENTO DE MONITOREO DE INFORMACION ASISTENCIA A MEDIOS Y APOYO A PRENSA'));
		Cargo::create(array('id'=>76,'nombre'=>'DEPARTAMENTO DE NORMATIVIDAD'));
		Cargo::create(array('id'=>77,'nombre'=>'DEPARTAMENTO DE NOTIFICACIONES'));
		Cargo::create(array('id'=>78,'nombre'=>'DEPARTAMENTO DE OPERACION Y MANTENIMIENTO DEL AMBIENTE FISICO'));
		Cargo::create(array('id'=>79,'nombre'=>'DEPARTAMENTO DE OPINIONES DE DESCLASIFICACION A'));
		Cargo::create(array('id'=>80,'nombre'=>'DEPARTAMENTO DE OPINIONES DE DESCLASIFICACION B'));
		Cargo::create(array('id'=>81,'nombre'=>'DEPARTAMENTO DE PLANEACION'));
		Cargo::create(array('id'=>82,'nombre'=>'DEPARTAMENTO DE POLITICAS DE PRIVACIDAD'));
		Cargo::create(array('id'=>83,'nombre'=>'DEPARTAMENTO DE PRESTACIONES Y SERVICIOS AL PERSONAL'));
		Cargo::create(array('id'=>84,'nombre'=>'DEPARTAMENTO DE PROCESOS Y PROCEDIMIENTOS'));
		Cargo::create(array('id'=>85,'nombre'=>'DEPARTAMENTO DE PRODUCCION EDITORIAL'));
		Cargo::create(array('id'=>86,'nombre'=>'DEPARTAMENTO DE PROGRAMACION DE CAPACITACION DE ACCESO'));
		Cargo::create(array('id'=>87,'nombre'=>'DEPARTAMENTO DE PROMOCION A'));
		Cargo::create(array('id'=>88,'nombre'=>'DEPARTAMENTO DE PROMOCION B'));
		Cargo::create(array('id'=>89,'nombre'=>'DEPARTAMENTO DE PROMOCION Y SEGUIMIENTO'));
		Cargo::create(array('id'=>90,'nombre'=>'DEPARTAMENTO DE PROSPECTIVA REGULATORIA'));
		Cargo::create(array('id'=>91,'nombre'=>'DEPARTAMENTO DE PROYECCION A'));
		Cargo::create(array('id'=>92,'nombre'=>'DEPARTAMENTO DE PROYECCION B'));
		Cargo::create(array('id'=>93,'nombre'=>'DEPARTAMENTO DE PROYECTOS A'));
		Cargo::create(array('id'=>94,'nombre'=>'DEPARTAMENTO DE PROYECTOS B'));
		Cargo::create(array('id'=>95,'nombre'=>'DEPARTAMENTO DE REDACCION A'));
		Cargo::create(array('id'=>96,'nombre'=>'DEPARTAMENTO DE REDACCION B'));
		Cargo::create(array('id'=>97,'nombre'=>'DEPARTAMENTO DE REGISTRO'));
		Cargo::create(array('id'=>98,'nombre'=>'DEPARTAMENTO DE REPORTES'));
		Cargo::create(array('id'=>99,'nombre'=>'DEPARTAMENTO DE REVISION RECURSAL'));
		Cargo::create(array('id'=>100,'nombre'=>'DEPARTAMENTO DE SEGUIMIENTO A INCONFORMIDADES A'));
		Cargo::create(array('id'=>101,'nombre'=>'DEPARTAMENTO DE SEGUIMIENTO A INCONFORMIDADES B'));
		Cargo::create(array('id'=>102,'nombre'=>'DEPARTAMENTO DE SEGUIMIENTO A RESOLUCIONES A'));
		Cargo::create(array('id'=>103,'nombre'=>'DEPARTAMENTO DE SEGUIMIENTO A RESOLUCIONES B'));
		Cargo::create(array('id'=>104,'nombre'=>'DEPARTAMENTO DE SEGUIMIENTO A RESOLUCIONES C'));
		Cargo::create(array('id'=>105,'nombre'=>'DEPARTAMENTO DE SEGUIMIENTO DE INFORMACION A'));
		Cargo::create(array('id'=>106,'nombre'=>'DEPARTAMENTO DE SEGUIMIENTO DE INFORMACION B'));
		Cargo::create(array('id'=>107,'nombre'=>'DEPARTAMENTO DE SEGUIMIENTO Y CONTROL DE CONVENIOS'));
		Cargo::create(array('id'=>108,'nombre'=>'DEPARTAMENTO DE SEGUIMIENTO Y ENLACE'));
		Cargo::create(array('id'=>109,'nombre'=>'DEPARTAMENTO DE SEGURIDAD DE LA INFORMACION A'));
		Cargo::create(array('id'=>110,'nombre'=>'DEPARTAMENTO DE SELECCION DE PERSONAL'));
		Cargo::create(array('id'=>111,'nombre'=>'DEPARTAMENTO DE SISTEMAS DE ACCESO A LA INFORMACION'));
		Cargo::create(array('id'=>112,'nombre'=>'DEPARTAMENTO DE SOPORTE TECNICO DE ASISTENCIA A ESCRITORIO'));
		Cargo::create(array('id'=>113,'nombre'=>'DEPARTAMENTO DE SUPERVISION Y ASESORIA A'));
		Cargo::create(array('id'=>114,'nombre'=>'DEPARTAMENTO DE SUPERVISION Y ASESORIA B'));
		Cargo::create(array('id'=>115,'nombre'=>'DEPARTAMENTO DE SUPERVISION Y ASESORIA C'));
		Cargo::create(array('id'=>116,'nombre'=>'DEPARTAMENTO DE SUPERVISION Y ASESORIA D'));
		Cargo::create(array('id'=>117,'nombre'=>'DEPARTAMENTO DE SUPERVISION Y ASESORIA E'));
		Cargo::create(array('id'=>118,'nombre'=>'DEPARTAMENTO DE SUPERVISION Y ASESORIA F'));
		Cargo::create(array('id'=>119,'nombre'=>'DEPARTAMENTO DE SUPERVISION Y ASESORIA G'));
		Cargo::create(array('id'=>120,'nombre'=>'DEPARTAMENTO DE SUSTANCIACION Y PROYECTOS A'));
		Cargo::create(array('id'=>121,'nombre'=>'DEPARTAMENTO DE SUSTANCIACION Y PROYECTOS B'));
		Cargo::create(array('id'=>122,'nombre'=>'DEPARTAMENTO DE TELECOMUNICACIONES'));
		Cargo::create(array('id'=>123,'nombre'=>'DEPARTAMENTO DE TELEVISION A'));
		Cargo::create(array('id'=>124,'nombre'=>'DEPARTAMENTO DE TELEVISION B'));
		Cargo::create(array('id'=>125,'nombre'=>'DEPARTAMENTO DE TESORERIA'));
		Cargo::create(array('id'=>126,'nombre'=>'DEPARTAMENTO DE TRAMITACION RECURSAL A'));
		Cargo::create(array('id'=>127,'nombre'=>'DEPARTAMENTO DE TRAMITACION RECURSAL B'));
		Cargo::create(array('id'=>128,'nombre'=>'DEPARTAMENTO DE VERIFICACION DE MATERIA DE DATOS PERSONALES B'));
		Cargo::create(array('id'=>129,'nombre'=>'DEPARTAMENTO DE VERIFICACION EN MATERIA DE DATOS PERSONALES A'));
		Cargo::create(array('id'=>130,'nombre'=>'DEPARTAMENTO DE VERIFICACION EN MATERIA DE DATOS PERSONALES C'));
		Cargo::create(array('id'=>131,'nombre'=>'DEPARTAMENTO DE VERIFICACION EN MATERIA DE DATOS PERSONALES D'));
		Cargo::create(array('id'=>132,'nombre'=>'DEPARTAMENTO DE VERIFICACION VOLUNTARIA A'));
		Cargo::create(array('id'=>133,'nombre'=>'DEPARTAMENTO DE VERIFICACION VOLUNTARIA B'));
		Cargo::create(array('id'=>134,'nombre'=>'DEPARTAMENTO DE VERIFICACION VOLUNTARIA C'));
		Cargo::create(array('id'=>135,'nombre'=>'DEPARTAMENTO DE VERIFICACION VOLUNTARIA D'));
		Cargo::create(array('id'=>136,'nombre'=>'DEPARTAMENTO DE VINCULACION CON MEDIOS Y CORRESPONSALES EXTRANJEROS A'));
		Cargo::create(array('id'=>137,'nombre'=>'DEPARTAMENTO DE VINCULACION CON MEDIOS Y CORRESPONSALES EXTRANJEROS B'));
		Cargo::create(array('id'=>138,'nombre'=>'DIRECCION DE ANALISIS Y ESTUDIOS DE PONENCIA'));
		Cargo::create(array('id'=>139,'nombre'=>'DIRECCION DE ASUNTOS INTERNACIONALES DE ACCESO'));
		Cargo::create(array('id'=>140,'nombre'=>'DIRECCION DE ASUNTOS INTERNACIONALES DE DATOS'));
		Cargo::create(array('id'=>141,'nombre'=>'DIRECCION DE ATENCION REGIONAL'));
		Cargo::create(array('id'=>142,'nombre'=>'DIRECCION DE CAPACITACION'));
		Cargo::create(array('id'=>143,'nombre'=>'DIRECCION DE COORDINACION Y EVALUACION'));
		Cargo::create(array('id'=>144,'nombre'=>'DIRECCION DE COORDINACION Y SEGUIMIENTO'));
		Cargo::create(array('id'=>145,'nombre'=>'DIRECCION DE DESARROLLO DE ESTRATEGIA'));
		Cargo::create(array('id'=>146,'nombre'=>'DIRECCION DE DESARROLLO HUMANO Y ORGANIZACIONAL'));
		Cargo::create(array('id'=>147,'nombre'=>'DIRECCION DE DIFUSION'));
		Cargo::create(array('id'=>148,'nombre'=>'DIRECCION DE ESQUEMAS DE AUTORREGULACION'));
		Cargo::create(array('id'=>149,'nombre'=>'DIRECCION DE ESTUDIOS'));
		Cargo::create(array('id'=>150,'nombre'=>'DIRECCION DE FACILITACION'));
		Cargo::create(array('id'=>151,'nombre'=>'DIRECCION DE FACILITACION DE POLITICAS'));
		Cargo::create(array('id'=>152,'nombre'=>'DIRECCION DE GESTION DOCUMENTAL'));
		Cargo::create(array('id'=>153,'nombre'=>'DIRECCION DE INSPECCION'));
		Cargo::create(array('id'=>154,'nombre'=>'DIRECCION DE INVESTIGACION'));
		Cargo::create(array('id'=>155,'nombre'=>'DIRECCION DE LO CONSULTIVO'));
		Cargo::create(array('id'=>156,'nombre'=>'DIRECCION DE LO CONTENCIOSO DE ACCESO'));
		Cargo::create(array('id'=>157,'nombre'=>'DIRECCION DE LO CONTENCIOSO DE DATOS'));
		Cargo::create(array('id'=>158,'nombre'=>'DIRECCION DE MEDIOS'));
		Cargo::create(array('id'=>159,'nombre'=>'DIRECCION DE NORMATIVIDAD'));
		Cargo::create(array('id'=>160,'nombre'=>'DIRECCION DE NORMATIVIDAD DE PROTECCION DE DATOS'));
		Cargo::create(array('id'=>161,'nombre'=>'DIRECCION DE ORIENTACION CONSULTA'));
		Cargo::create(array('id'=>162,'nombre'=>'DIRECCION DE POLITICAS DE DESCLASIFICACION'));
		Cargo::create(array('id'=>163,'nombre'=>'DIRECCION DE PROMOCION'));
		Cargo::create(array('id'=>164,'nombre'=>'DIRECCION DE RECURSOS FINANCIEROS'));
		Cargo::create(array('id'=>165,'nombre'=>'DIRECCION DE RECURSOS MATERIALES'));
		Cargo::create(array('id'=>166,'nombre'=>'DIRECCION DE RELACIONES INTERINSTITUCIONALES Y PUBLICAS'));
		Cargo::create(array('id'=>167,'nombre'=>'DIRECCION DE SANCIONES'));
		Cargo::create(array('id'=>168,'nombre'=>'DIRECCION DE SEGUIMIENTO A RESOLUCIONES'));
		Cargo::create(array('id'=>169,'nombre'=>'DIRECCION DE SERVICIO DE INFORMACION Y DOCUMENTACION'));
		Cargo::create(array('id'=>170,'nombre'=>'DIRECCION DE SISTEMAS'));
		Cargo::create(array('id'=>171,'nombre'=>'DIRECCION DE SOLUCIONES TECNOLOGICAS'));
		Cargo::create(array('id'=>172,'nombre'=>'DIRECCION DE SUSTANCIACION DE PROTECCION DE DERECHOS A'));
		Cargo::create(array('id'=>173,'nombre'=>'DIRECCION DE SUSTANCIACION DE PROTECCION DE DERECHOS B'));
		Cargo::create(array('id'=>174,'nombre'=>'DIRECCION DE TRAMITACION Y SUSTANCIACION'));
		Cargo::create(array('id'=>175,'nombre'=>'DIRECCION DE VERIFICACION'));
		Cargo::create(array('id'=>176,'nombre'=>'DIRECCION DE VIGILANCIA'));
		Cargo::create(array('id'=>177,'nombre'=>'DIRECCION DE VINCULACION CON LA SOCIEDAD'));
		Cargo::create(array('id'=>178,'nombre'=>'DIRECCION GENERAL DE ADMINISTRACION'));
		Cargo::create(array('id'=>179,'nombre'=>'DIRECCION GENERAL DE ANALISIS NORMATIVO Y EVALUACION DE LA INFORMACION'));
		Cargo::create(array('id'=>180,'nombre'=>'DIRECCION GENERAL DE ASUNTOS INTERNACIONALES'));
		Cargo::create(array('id'=>181,'nombre'=>'DIRECCION GENERAL DE ASUNTOS JURIDICOS'));
		Cargo::create(array('id'=>182,'nombre'=>'DIRECCION GENERAL DE AUTORREGULACION'));
		Cargo::create(array('id'=>183,'nombre'=>'DIRECCION GENERAL DE CAPACITACION PROMOCION Y RELACIONES INSTITUCIONALES'));
		Cargo::create(array('id'=>184,'nombre'=>'DIRECCION GENERAL DE COMUNICACION SOCIAL Y DIFUSION'));
		Cargo::create(array('id'=>185,'nombre'=>'DIRECCION GENERAL DE COORDINACION DE POLITICAS DE ACCESO'));
		Cargo::create(array('id'=>186,'nombre'=>'DIRECCION GENERAL DE COORDINACION Y VIGILANCIA DE LA APF'));
		Cargo::create(array('id'=>187,'nombre'=>'DIRECCION GENERAL DE GESTION DE INFORMACION Y ESTUDIOS'));
		Cargo::create(array('id'=>188,'nombre'=>'DIRECCION GENERAL DE NORMATIVIDAD CONSULTA Y ATENCION REGIONAL'));
		Cargo::create(array('id'=>189,'nombre'=>'DIRECCION GENERAL DE SUSTANCIACION Y SANCION'));
		Cargo::create(array('id'=>190,'nombre'=>'DIRECCION GENERAL DE TECNOLOGIAS DE LA INFORMACION'));
		Cargo::create(array('id'=>191,'nombre'=>'DIRECCION GENERAL DE VERIFICACION'));
		Cargo::create(array('id'=>192,'nombre'=>'DIRECTOR DE AUDITORIA INTERNA AUDITOR'));
		Cargo::create(array('id'=>193,'nombre'=>'DIRECTOR DE AUDITORIA PARA EL DESARROLLO Y MEJORA DE LA GESTION PUBLICA'));
		Cargo::create(array('id'=>194,'nombre'=>'DIRECTOR DE QUEJAS ABOGADO'));
		Cargo::create(array('id'=>195,'nombre'=>'DIRECTOR DE RESPONSABILIDADES ABOGADO'));
		Cargo::create(array('id'=>196,'nombre'=>'ENLACE'));
		Cargo::create(array('id'=>197,'nombre'=>'ENLACE DE PONENCIA A'));
		Cargo::create(array('id'=>198,'nombre'=>'ENLACE DE PONENCIA B'));
		Cargo::create(array('id'=>199,'nombre'=>'ENLACE DE PONENCIA C'));
		Cargo::create(array('id'=>200,'nombre'=>'JEFATURA WEB'));
		Cargo::create(array('id'=>201,'nombre'=>'PLENO'));
		Cargo::create(array('id'=>202,'nombre'=>'PROYECTISTA DE ACCESO A LA INFORMACION A'));
		Cargo::create(array('id'=>203,'nombre'=>'PROYECTISTA DE ACCESO A LA INFORMACION B'));
		Cargo::create(array('id'=>204,'nombre'=>'PROYECTISTA DE ACCESO A LA INFORMACION C'));
		Cargo::create(array('id'=>205,'nombre'=>'PROYECTISTA DE ACCESO A LA INFORMACION D'));
		Cargo::create(array('id'=>206,'nombre'=>'PROYECTISTA DE PROTECCION DE DATOS A'));
		Cargo::create(array('id'=>207,'nombre'=>'PROYECTISTA DE PROTECCION DE DATOS B'));
		Cargo::create(array('id'=>208,'nombre'=>'SECRETARIA'));
		Cargo::create(array('id'=>209,'nombre'=>'SECRETARIA DE ACCESO A LA INFORMACION COORDINACION DE ACCESO A LA INFORMACION'));
		Cargo::create(array('id'=>210,'nombre'=>'SECRETARIA DE ACUERDOS Y PONENCIA DE ACCESO A LA INFORMACION'));
		Cargo::create(array('id'=>211,'nombre'=>'SECRETARIA DE ACUERDOS Y PONENCIA DE DATOS PERSONALES'));
		Cargo::create(array('id'=>212,'nombre'=>'SECRETARIA DE PROTECCION DE DATOS COORDINACION DE PROTECCION DE DATOS'));
		Cargo::create(array('id'=>213,'nombre'=>'SECRETARIA GENERAL COORDINACION EJECUTIVA'));
		Cargo::create(array('id'=>214,'nombre'=>'SECRETARIA PARTICULAR'));
		Cargo::create(array('id'=>215,'nombre'=>'SECRETARIA TECNICA DEL PLENO'));
		Cargo::create(array('id'=>216,'nombre'=>'SUBDIRECCION DE ADQUISICIONES Y CONTROL PATRIMONIAL'));
		Cargo::create(array('id'=>217,'nombre'=>'SUBDIRECCION DE ANALISIS'));
		Cargo::create(array('id'=>218,'nombre'=>'SUBDIRECCION DE ANALISIS Y ESTUDIOS DE PONENCIA'));
		Cargo::create(array('id'=>219,'nombre'=>'SUBDIRECCION DE APLICACIONES WEB'));
		Cargo::create(array('id'=>220,'nombre'=>'SUBDIRECCION DE ARCHIVOS'));
		Cargo::create(array('id'=>221,'nombre'=>'SUBDIRECCION DE ASUNTOS INTERNACIONALES DE ACCESO'));
		Cargo::create(array('id'=>222,'nombre'=>'SUBDIRECCION DE ASUNTOS INTERNACIONALES DE DATOS'));
		Cargo::create(array('id'=>223,'nombre'=>'SUBDIRECCION DE ATENCION A LOS PARTICULARES'));
		Cargo::create(array('id'=>224,'nombre'=>'SUBDIRECCION DE ATENCION REGIONAL CENTRO'));
		Cargo::create(array('id'=>225,'nombre'=>'SUBDIRECCION DE ATENCION REGIONAL NORTE'));
		Cargo::create(array('id'=>226,'nombre'=>'SUBDIRECCION DE ATENCION REGIONAL SUR'));
		Cargo::create(array('id'=>227,'nombre'=>'SUBDIRECCION DE CALIDAD E IMPLANTACION'));
		Cargo::create(array('id'=>228,'nombre'=>'SUBDIRECCION DE CERTIFICACION'));
		Cargo::create(array('id'=>229,'nombre'=>'SUBDIRECCION DE CONCILIACION FORANEA'));
		Cargo::create(array('id'=>230,'nombre'=>'SUBDIRECCION DE CONCILIACION LOCAL'));
		Cargo::create(array('id'=>231,'nombre'=>'SUBDIRECCION DE CONTROL DE INGRESOS Y NOMINA'));
		Cargo::create(array('id'=>232,'nombre'=>'SUBDIRECCION DE CONVENIOS Y RECOMENDACIONES'));
		Cargo::create(array('id'=>233,'nombre'=>'SUBDIRECCION DE COORDINACION INTERNA'));
		Cargo::create(array('id'=>234,'nombre'=>'SUBDIRECCION DE COORDINACION Y CONSULTAS'));
		Cargo::create(array('id'=>235,'nombre'=>'SUBDIRECCION DE DESARROLLO'));
		Cargo::create(array('id'=>236,'nombre'=>'SUBDIRECCION DE DESARROLLO DE CAPACITACION DE ACCESO'));
		Cargo::create(array('id'=>237,'nombre'=>'SUBDIRECCION DE DESARROLLO DE CAPACITACION DE DATOS'));
		Cargo::create(array('id'=>238,'nombre'=>'SUBDIRECCION DE DESARROLLO ORGANIZACIONAL'));
		Cargo::create(array('id'=>239,'nombre'=>'SUBDIRECCION DE DISCURSOS'));
		Cargo::create(array('id'=>240,'nombre'=>'SUBDIRECCION DE DIVULGACION Y LOGISTICA'));
		Cargo::create(array('id'=>241,'nombre'=>'SUBDIRECCION DE ENLACE CON EL SECTOR PRIVADO'));
		Cargo::create(array('id'=>242,'nombre'=>'SUBDIRECCION DE ENLACE CON LA SOCIEDAD ORGANIZADA'));
		Cargo::create(array('id'=>243,'nombre'=>'SUBDIRECCION DE ENLACE CON MEDIOS ELECTRONICOS'));
		Cargo::create(array('id'=>244,'nombre'=>'SUBDIRECCION DE ESTADOS Y MUNICIPIOS'));
		Cargo::create(array('id'=>245,'nombre'=>'SUBDIRECCION DE ESTUDIOS'));
		Cargo::create(array('id'=>246,'nombre'=>'SUBDIRECCION DE ESTUDIOS DE CLASIFICACION'));
		Cargo::create(array('id'=>247,'nombre'=>'SUBDIRECCION DE EVALUACION'));
		Cargo::create(array('id'=>248,'nombre'=>'SUBDIRECCION DE FACILITACION'));
		Cargo::create(array('id'=>249,'nombre'=>'SUBDIRECCION DE GESTION'));
		Cargo::create(array('id'=>250,'nombre'=>'SUBDIRECCION DE INVESTIGACION A'));
		Cargo::create(array('id'=>251,'nombre'=>'SUBDIRECCION DE INVESTIGACION B'));
		Cargo::create(array('id'=>252,'nombre'=>'SUBDIRECCION DE LO CONSULTIVO'));
		Cargo::create(array('id'=>253,'nombre'=>'SUBDIRECCION DE LO CONTENCIOSO DE ACCESO'));
		Cargo::create(array('id'=>254,'nombre'=>'SUBDIRECCION DE LO CONTENCIOSO DE DATOS'));
		Cargo::create(array('id'=>255,'nombre'=>'SUBDIRECCION DE MEDIOS'));
		Cargo::create(array('id'=>256,'nombre'=>'SUBDIRECCION DE NORMATIVIDAD'));
		Cargo::create(array('id'=>257,'nombre'=>'SUBDIRECCION DE OPERACIONES'));
		Cargo::create(array('id'=>258,'nombre'=>'SUBDIRECCION DE OPINIONES DE DESCLASIFICACION'));
		Cargo::create(array('id'=>259,'nombre'=>'SUBDIRECCION DE ORIENTACION Y CONSULTA'));
		Cargo::create(array('id'=>260,'nombre'=>'SUBDIRECCION DE OSOS'));
		Cargo::create(array('id'=>261,'nombre'=>'SUBDIRECCION DE PLANEACION'));
		Cargo::create(array('id'=>262,'nombre'=>'SUBDIRECCION DE PLANEACION ESTRATEGICA'));
		Cargo::create(array('id'=>263,'nombre'=>'SUBDIRECCION DE POLITICAS DE PRIVACIDAD'));
		Cargo::create(array('id'=>264,'nombre'=>'SUBDIRECCION DE PRACTICAS DE GOBIERNO'));
		Cargo::create(array('id'=>265,'nombre'=>'SUBDIRECCION DE PROGRAMACION DE CAPACITACION DE ACCESO'));
		Cargo::create(array('id'=>266,'nombre'=>'SUBDIRECCION DE PROGRAMACION Y PRESUPUESTO'));
		Cargo::create(array('id'=>267,'nombre'=>'SUBDIRECCION DE PROMOCION Y VINCULACION CON SECTORES PUBLICO Y PRIVADO'));
		Cargo::create(array('id'=>268,'nombre'=>'SUBDIRECCION DE PROSPECTIVA REGULATORIA'));
		Cargo::create(array('id'=>269,'nombre'=>'SUBDIRECCION DE PROTOCOLO'));
		Cargo::create(array('id'=>270,'nombre'=>'SUBDIRECCION DE PROYECTOS'));
		Cargo::create(array('id'=>271,'nombre'=>'SUBDIRECCION DE REGISTRO'));
		Cargo::create(array('id'=>272,'nombre'=>'SUBDIRECCION DE RESOLUCION Y CONTROL A'));
		Cargo::create(array('id'=>273,'nombre'=>'SUBDIRECCION DE RESOLUCION Y CONTROL B'));
		Cargo::create(array('id'=>274,'nombre'=>'SUBDIRECCION DE RESOLUCIONES DE ACCESO A LA INFORMACION A'));
		Cargo::create(array('id'=>275,'nombre'=>'SUBDIRECCION DE RESOLUCIONES DE ACCESO A LA INFORMACION B'));
		Cargo::create(array('id'=>276,'nombre'=>'SUBDIRECCION DE RESOLUCIONES DE PROTECCION DE DATOS'));
		Cargo::create(array('id'=>277,'nombre'=>'SUBDIRECCION DE RESOLUCIONES EN MATERIA DE PROTECCION DE DERECHOS'));
		Cargo::create(array('id'=>278,'nombre'=>'SUBDIRECCION DE RESOLUCIONES EN MATERIA DE VERIFICACION'));
		Cargo::create(array('id'=>279,'nombre'=>'SUBDIRECCION DE SEGUIMIENTO A INCONFORMIDADES'));
		Cargo::create(array('id'=>280,'nombre'=>'SUBDIRECCION DE SEGUIMIENTO A RESOLUCIONES'));
		Cargo::create(array('id'=>281,'nombre'=>'SUBDIRECCION DE SEGURIDAD DE LA INFORMACION'));
		Cargo::create(array('id'=>282,'nombre'=>'SUBDIRECCION DE SERVICIO PROFESIONAL'));
		Cargo::create(array('id'=>283,'nombre'=>'SUBDIRECCION DE SERVICIOS GENERALES'));
		Cargo::create(array('id'=>284,'nombre'=>'SUBDIRECCION DE SISTEMAS DE ACCESO A LA INFORMACION'));
		Cargo::create(array('id'=>285,'nombre'=>'SUBDIRECCION DE SISTEMAS DE PROTECCION DE DATOS'));
		Cargo::create(array('id'=>286,'nombre'=>'SUBDIRECCION DE SUSTANCIACION'));
		Cargo::create(array('id'=>287,'nombre'=>'SUBDIRECCION DE SUSTANCIACION A'));
		Cargo::create(array('id'=>288,'nombre'=>'SUBDIRECCION DE SUSTANCIACION B'));
		Cargo::create(array('id'=>289,'nombre'=>'SUBDIRECCION DE TELEVISION'));
		Cargo::create(array('id'=>290,'nombre'=>'SUBDIRECCION DE TESORERIA Y CONTABILIDAD'));
		Cargo::create(array('id'=>291,'nombre'=>'SUBDIRECCION DE VERIFICACION EN MATERIA DE DATOS PERSONALES A'));
		Cargo::create(array('id'=>292,'nombre'=>'SUBDIRECCION DE VERIFICACION EN MATERIA DE DATOS PERSONALES B'));
		Cargo::create(array('id'=>293,'nombre'=>'SUBDIRECCION DE VERIFICACION VOLUNTARIA A'));
		Cargo::create(array('id'=>294,'nombre'=>'SUBDIRECCION DE VERIFICACION VOLUNTARIA B'));
		Cargo::create(array('id'=>295,'nombre'=>'SUBDIRECCION DE VERIFICACION VOLUNTARIA C'));
		Cargo::create(array('id'=>296,'nombre'=>'SUBDIRECCION DE VIGILANCIA'));
		Cargo::create(array('id'=>297,'nombre'=>'SUBDIRECTOR A'));
		Cargo::create(array('id'=>298,'nombre'=>'SUBDIRECTOR AUDITOR'));
		Cargo::create(array('id'=>299,'nombre'=>'SUBDIRECTOR CONSULTOR'));
		Cargo::create(array('id'=>300,'nombre'=>'SUBDIRECTOR DE QUEJAS ABOGADO'));
		Cargo::create(array('id'=>301,'nombre'=>'SUBDIRECTOR DE RESPONSABILIDADES ABOGADO'));
		Cargo::create(array('id'=>302,'nombre'=>'TITULAR DE AUDITORIA INTERNA Y TITULAR DEL AREA DE AUDITORIA PARA EL DESARROLLO Y MEJORA DE LA GESTION PUBLICA'));
		Cargo::create(array('id'=>303,'nombre'=>'TITULAR RESPONSABILIDADES Y QUEJAS'));
    }
}

